### ISSUE TITLE
How data is read

### ISSUE THREAD

**Issue by joery1337** [ClitherProject/Slither.io-Protocol#1]
Hey,

I saw you had some questions on Reddit, I'm not sure if this will help but atleast I tried.

Variable `c` is the byte array.

`(c[b] << 8 | c[b + 1]) / 100` for example is a 2 bytes number with 3 decimal places.

`grd = c[b] << 16 | c[b + 1] << 8 | c[b + 2];` = the game radius, this is a 3 byte number.

Server side, you just need to do the opposite.

https://gist.github.com/joery1337/6eae1e90f47be9d4431e12fbec3fed3e, line 4462

**Comment by ThunderGemios10** [comment]
Can you put it on Protocol.md? The template follows: https://github.com/OgarioProject/Agar.io-Protocol/blob/master/Protocol.md

**Comment by joery1337** [comment]
I really don't have time at the moment, here are two examples:

```
var exampleNumber = 1337;

var bytes = [];
bytes[0] = (exampleNumber >> 8 & 0xFF);
bytes[1] = (exampleNumber & 0xFF);

var readNumber = (bytes[0] << 8 | bytes[1]); // 2 byte number

console.log(exampleNumber, readNumber);
```

```
var exampleDecimal = 420.69 * 100; //  multiply by 100 server side

var bytes = [];
bytes[0] = (exampleDecimal >> 8 & 0xFF);
bytes[1] = (exampleDecimal & 0xFF);

var readDecimal = (bytes[0] << 8 | bytes[1]) / 100; // 2 byte decimal, divide by 100 client side

console.log(readDecimal);
```

**Comment by ThunderGemios10** [comment]
@joery1337 What are those for?

**Comment by joery1337** [comment]
It's an example of how to read and write those bytes the way it's done in Slither.io

**Comment by ThunderGemios10** [comment]
@joery1337 Ah i see..

**Comment by ThunderGemios10** [comment]
@joery1337 As of the moment, I need it documented at Protocol.md.. Let me know if you have made a pull request for it... You can take your time..

**Comment by Mat2095** [comment]
I doubt he will come back...
