### ISSUE TITLE
Sectors

### ISSUE THREAD

**Issue by ObsidianLarin** [ClitherProject/Slither.io-Protocol#19]
What are sectors actually mean? In 'a' packet(initial setup) third and fourth values are describing something named "sectors". But what it really are?

**Comment by ThunderGemios10** [comment]
No one really knows.. But its a packet that is required to be implemented.

**Comment by circa94** [comment]
I know what they are... The whole map is splitted into sectors. like a grid or a tiled map. The client is only rendering sectors which are nearby your snake, also only the snakes and foods which are on these sectors.
If you use the mod where you can zoom in and out ingame, you can perfectly see how it works.

**Comment by ObsidianLarin** [comment]
But if sector size is 480 and sector count is 130, 480 \* 130 = 62400. It's greater than map diameter(43200). How it's possible?

**Comment by Mat2095** [comment]
Activate testing in the game.js (first line: var testing = 1;) and you can see the sectors. The loaded ones are green; some on the edge might not be loaded, then they aren't green.

130 is the sector_count_ALONG_EDGE, which is a circle. In the radius there should be 21600/480=45 sectors, and 130/45=2,888889, which is too close to PI to be a coincidence for me... I know it should be 2*PI though :(

**Comment by sitano** [comment]
Its actually 144. Client's default overridden by  server's init packet. https://github.com/sitano/slitherss/blob/master/src/game/config.h#L20

**Comment by Mat2095** [comment]
Ok, now this makes sense. I think back then the server sent sector_size 480 and sector_count 130 but changed that to 300 / 144 with protocol version 7 or 8.
It's still unused in the client ^^
