### ISSUE TITLE
How to inspect websocket packets to decode protocol

### ISSUE THREAD

**Issue by brianbreitsch** [ClitherProject/Slither.io-Protocol#20]
I'm trying to understand y'all are figuring out the Slither.io protocol.

I have Wireshark running and I'm looking for websocket packets sent to the slither.io server, but they all seem to have a payload of length 0 or 1.

How is it that you guys are able to figure out what you have about the protocol?  I would love to be able to help.

**Comment by ThunderGemios10** [comment]
We have already figured out most of the packets, You can see Protocol.md for details.
If you find anything useful, Feel free to open a pull request !

**Comment by brianbreitsch** [comment]
Could you elaborate on how you accomplished what is in Protocol.md?  And is there a method/plan for validating what is written there?

**Comment by ThunderGemios10** [comment]
@brianbreitsch You may want to ask @Kogs and @circa94 They mostly found out.. well... almost everything..

**Comment by brianbreitsch** [comment]
Okay thanks--yeah @Kogs  or @circa94 if you read this, I'm wondering if you used Wireshark to figure out the protocol, and why I'm not seeing the messages I'd expect in the payloads.

**Comment by Kogs** [comment]
@brianbreitsch i tried using wireshark but the Best way is to look into the Javascript Code of the game, to unterstand how the protocol works an what which Massage means.

**Comment by brianbreitsch** [comment]
@Kogs Okay--yeah--I think their actual messages may be getting split into several websocket packets.
I beautified the clientside js, but man is it still ugly.  There are a lot of canvas creations in there--any tips on how to figure out which canvas all the snakes/food are drawn on?  I haven't been able to figure out which variables represent game state.

**Comment by Kogs** [comment]
Thats exactly the problem we have. The JS Code is ugly as Sh't and its hard to figure out witch message changes what. There are 2 Canvas I think one is the game and one is the minimap. Why should they split the messages into several websocket packets? That makes no sense for me, because  you would have mutch more over head.

**Comment by ThunderGemios10** [comment]
@Kogs I think the devs did that on purpose to make it complicated and it would make it hard for someone to research the protocol, and yet, we managed to research most of the packets.

**Comment by brianbreitsch** [comment]
Yes, and yes.  I think there are even more than 2 canvases--I'm pretty sure one of them does the animation at the beginning.
@ThunderGemios10 A lot of the ugliness should just be a result of minification--but yeah--the code is so arcane that some of it could definitely be purposeful.
@Kogs The message-splitting would happen on the websocket protocol level--so the clientside code wouldn't necessarily "notice" it.  It would only show up when inspecting the individual websocket packets, e.g. via Wireshark.

**Comment by Kogs** [comment]
Ah ok. What we did was editing the game to log the traffic: https://github.com/circa94/JSlither/blob/master/tests/game-mods/traffic_loggin_on_message.js 
https://github.com/circa94/JSlither/blob/master/tests/traffic.log

**Comment by brianbreitsch** [comment]
Oh! Got it--
Quick question then--what do you know/understand about replacing the client js with the custom js?  I've heard you can use Greasemonkey/Tampermonkey for such things--is that what you do?

**Comment by Kogs** [comment]
no you dont realy need such tools. The easiest way is to override the functions.

Example the game has a function 
`function foo(){ ...}`
all you need to do is paste this in the javascript console of your browser
`foo = function(){your edited code}`
and then play the game.

**Comment by Kogs** [comment]
In the traffic_loggin_on_message.js it also should start with
`connect =  function()`
instead of
`function connect()`

see https://github.com/circa94/JSlither/blob/master/tests/game-mods/traffic_loggin_game_loop.js

**Comment by rockthrower69** [comment]
The protocol has changed. Look for this in the code: `if (5 <= protocol_version) {`

Bytheway, it isnt really clear how you can make your own server. I understand we have many packets, and their meaning. But there isn't stated anywhere which packets have to sent when and how often. This is a problem for me since I'm trying to build my own server.

**Comment by ThunderGemios10** [comment]
@rockthrower69 The protocol changes every update, Isn't it obvious? However the question is if its a major update or a minor update. Does it affect how packets work?

**Comment by Kogs** [comment]
The protocol changes Not every update.  The Part of Code   if (5 <= protocol_version) {    means this Part is there since the protocol Version 5. So if you always send the protocol Version 6 in the init packet to the Client nothing must changed on the Server

**Comment by Mat2095** [comment]
Another good way to replace the original client js with a custom one is this addon: https://chrome.google.com/webstore/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii
