### ISSUE TITLE
How to get gameradius 

### ISSUE THREAD

**Issue by chancity** [ClitherProject/Slither.io-Protocol#21]
I see gameradius mentioned a few times in the protocol.md.  How is this calculated or from what object can it be read?

**Comment by Kogs** [comment]
The gameradius is send from the server to the client in the [inital Packet ](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_a_detail)

**Comment by izanagi1995** [comment]
If you want it from the client, it's `grd`
