### ISSUE TITLE
protocol version

### ISSUE THREAD

**Issue by Mat2095** [ClitherProject/Slither.io-Protocol#24]
Hi,

I have some additional information (regarding the "w" and "W" packages), but they only apply to protocol version 8 (and above, most likely).
The documentation has a big heading saying "Protocol Version 6", are you only interested in version 6 or is this just not updated yet? In case you are interested in newer versions, do you want to keep the documentation about version 6 (e.g. in another branch)?

**Comment by ThunderGemios10** [comment]
The protocol documentation is outdated for now.. And no we have no interest of having older protocol documentation. If you can, You can update the protocol yourself.

Cheers!

**Comment by Mat2095** [comment]
Thanks for the answer. I'll do my best ;)
