### ISSUE TITLE
i was thinking about creating slither bots

### ISSUE THREAD

**Issue by ghost** [ClitherProject/Slither.io-Protocol#25]
as your finding packets maybe we can make slither bots together

**Comment by Mat2095** [comment]
What language would you use? With GUI or command-line? More like one or hundred bots at the same time?
In case you say Java, GUI, one bot at a time: I'm currently working on a project like this, probably soon on github.

**Comment by ghost** [comment]
can we work together

**Comment by ghost** [comment]
if yes give your skype id

**Comment by Mat2095** [comment]
When I look at your public "contributions", I only see you looking for people for slither-farm-bot-services. I will not support that.
I suggest you start your bot on your own, with the protocol-documentation here it shouldn't be too difficult.
If you want to, I can send you an email when my project is available. However, you would probably have to change too much to make it fit your needs, so I don't think it is worth it for you.

**Comment by ghost** [comment]
no i stoped thinking about the paid service i want it to be free if your wrking let me help you

**Comment by ghost** [comment]
and are you working on slither bots

**Comment by ghost** [comment]
hey @Mat2095 mat can i possibly get a link when your project is available? it sounds interesting

**Comment by dahquan** [comment]
You guys can take a look at my implementation of it here https://github.com/dahquan/rattlesnake

**Comment by ghost** [comment]
I did

**Comment by ghost** [comment]
I did

**Comment by Mat2095** [comment]
I've published my client, see https://github.com/Mat2095/MySlither. 
It's still in development, but already playable (I already got rank 3 with it ;) )
@Classicanon

**Comment by ghost** [comment]
okie
