### ISSUE TITLE
head.y and head.x of own snake (player)

### ISSUE THREAD

**Issue by agarioBotDev** [ClitherProject/Slither.io-Protocol#47]
hello,

head positions are also received in MoveSnake (of own snake)?
or in which is it received ?

greats,
david

**Comment by Mat2095** [comment]
The head-position is updated in the packets g, G, n and N. For g and n the coords are absolute, for G and N they are relative to the old head-position.

**Comment by agarioBotDev** [comment]
@Mat2095 g and G seems to sends positions of all snakes....i guess own snake has snakeID = 0 ?

greats,
david

**Comment by Mat2095** [comment]
Oh, now I understand.
No, the own snake has a random ID. The first snake you receive with the s packet is the own snake, that's how you can get the player's snake's id.

**Comment by agarioBotDev** [comment]
@Mat2095 thanks, I have now what I need :-). Does the id change on death ? Btw if you want you can work with me - I already had a paid agar.io bot service (d-bots.com) now after your information my slither bots should be fine too and ready for selling.

greats,
david

**Comment by Mat2095** [comment]
I haven't tested it, but I bet the id does change.

**Comment by izanagi1995** [comment]
I think there is a way in the client to have your own ID. Try something like `console.log(snake.id)`
Yes the ID is changing everytime your play a new game. When you die, snake.id becomes negative (why? I don't know, maybe killer ID) then snake becomes null due to resetGame()

**Comment by Mat2095** [comment]
When you die, it becones -1234, kind of a dummy-value, since the snake-object still exists, but isn't in the game and therefore doesn't have an id.

**Comment by izanagi1995** [comment]
Thank you @Mat2095 :)

**Comment by agarioBotDev** [comment]
@Mat2095 
I have a weird problem....

somehow the server never ever respond to my websocket requests - I tried to connect 100 bots from  usa ips, 300 from europe ips and 50 from Russia...always getting the error: socket hang up OR read ECONNRESET -> i mentioned maybe because of the proxies, so I made a js file with only the websocket in it....no send or anything like that and ofc no proxy agent -> still same error ?

You have/had same prob ?
It's rly unlucky because the hole client is done, but i cannot test without connection.... :(

greats,
david

**Comment by Mat2095** [comment]
You do need to send the init-packet.
However, in my client, I take the server-list and randomly try to connect to a server. Takes about 5-10 tries each time (maybe full servers?)

**Comment by agarioBotDev** [comment]
@Mat2095 

At the moment it seems like there's no init packet, just the 'spawn' packet.
The thing is it never open...
if it takes 5-10 times to connect at least 50 should connect then...but not even one connect - tried on different servers.

greats,
david

**Comment by Mat2095** [comment]
I think we are talking about the same packet, call it init, spawn or SetUsernameAndSkin.
I'm not sure, but I think you also have to send a ping packet.
Also make sure to add an 'Origin' argument to the websocket header with value 'http://slither.io'.
And try using another User-Agent, for example, the java-default one is blocked by CloudFlare.

**Comment by agarioBotDev** [comment]
@Mat2095 

Ok i use now the client of lib websocket, not ws.
It kind of works better in term of giving a better error message:

Error: Sec-WebSocket-Accept header from server didn't match expected value of X2nZ39p5dXoNZtD9lN70Xv1/Na8=

I guess it means the server sended a header the client didn't expect ?
If yes, you problably know how to accept all headers ?

greats,
david

**Comment by Mat2095** [comment]
So, you get this error before you even could send the first packet?

**Comment by agarioBotDev** [comment]
@Mat2095 

yes, the weird thing - about 15-25 of 300 clients connect, but disconnect after ~3 mins even though they send pings and the spawn packet on every detected death ( "v" ).

**Comment by Mat2095** [comment]
When you die, the connection will close after a few seconds and you have to connect again (again, try multiple times). You can't send another spawn packet on the same connection.

**Comment by Stan-Stani** [comment]
@agarioBotDev Have you figured out a fix for the "Sec-WebSocket-Accept header from server didn't match expected value of X2nZ39p5dXoNZtD9lN70Xv1/Na8=" issue? I'm using WebSocket-Node and getting the same problem sometimes too.

**Comment by Stan-Stani** [comment]
@Mat2095 Does it still always take you multiple tries to connect?

**Comment by Mat2095** [comment]
Yes. But since the original client takes multiple tries, too, I don't see this as a problem.
Also the official client uses more information from the server-list, probably for optimisation (see loadSos in the game.js).

**Comment by agarioBotDev** [comment]
@cyclingLinguist normally I do a prototype in javscript (node) for testing purpose. Then I switch to C# for the final version (better performance), because I have a paid bot service. I had the problem with the connection establishment so i instantly switched to C# where i can use RAW_SOCKETS and modify the connection itself. To Sum up, I built my client in C# with RAW_SOCKETS and accept all headers.

**Comment by Stan-Stani** [comment]
@Mat2095 @agarioBotDev  Thanks both of you for your help. I was able to modify the source code of the library I'm using to still connect even if the Sec-WebSocket-Accept header the server sends isn't the expected value. Now I can connect every time :) Thanks @agarioBotDev for explaining what you did.

**Comment by agarioBotDev** [comment]
@cyclingLinguist I guess you used my example client ?

**Comment by Stan-Stani** [comment]
@agarioBotDev Haha, no actually. I hadn't noticed it until you mentioned it here, but I did do almost the same thing you did to get it working. Now that I look at your client though, your method is cleaner. I actually literally modified WebSocketClient.js of the WebSocket-Node library to be 

```
 if (headers['sec-websocket-accept'] !== expectedKey) {

//        this.failHandshake('Sec-WebSocket-Accept header from server didn\'t match expected value of ' + expectedKey);

        console.log('Sec-WebSocket-Accept header from server didn\'t match expected value of ' + expectedKey + '... But connecting anyway...');
    }`
```

Your way is obviously better because I wouldn't actually have to modify the source code if I just redefine the prototype.
