### ISSUE TITLE
Suggestion: list of custom servers/clients

### ISSUE THREAD

**Issue by Mat2095** [ClitherProject/Slither.io-Protocol#49]
Hi,

I just thought that maybe it would be a nice idea to make a list of all custom server/client implementations.
Any opinions on that?

**Comment by sitano** [comment]
There are not much. Mainly 3.

**Comment by Mat2095** [comment]
Servers:
- https://github.com/ClitherProject/Clither-Server
- https://github.com/circa94/JSlither
- https://github.com/iiegor/slither

Clients:
- https://github.com/gegy1000/Slyther
- https://github.com/Mat2095/MySlither
- https://github.com/PlitherProject/Plither

**Comment by agarioBotDev** [comment]
@Mat2095 

started my client:

https://github.com/agarioBotDev/Slither.io-Client

**Comment by RowanHarley** [comment]
@Mat2095 could you add my server: https://github.com/RowanHarley/Slither-Server

**Comment by Mat2095** [comment]
I've just created the list, including the ones from @agarioBotDev and @RowanHarley .
