### ISSUE TITLE
How to build basic client to connect to slither.io server? Do I need to establish WSS connection?

### ISSUE THREAD

**Issue by Stan-Stani** [ClitherProject/Slither.io-Protocol#50]
Hey guys,

I'm trying to use the Net  module of Node.js to talk to a slither.io server. However, I've only gotten as far as opening the connection. The server won't respond to anything I send it.

I've tried something like this:

```
var packetSetUsernameAndSkin = new Buffer([115, 7, 0, 115]);
var packetPing = new Buffer([251]);

client.write(packetSetUsernameAndSkin);
client.write(packetPing);
```

Yet the server still doesn't respond. I must be missing something. Do I need to establish a SSL connection or something? Wireshark seems to indicate that the connection is over websockets, so I guess I do have to establish a secure websocket connection. Any advice on doing that?

(I'm sorry if this isn't the right place to ask!)

P.S. Love the work you guys are doing. Looking at the protocol is fun!

**Comment by Mat2095** [comment]
No, the connections are not secure:
`ws = new WebSocket("ws://" + bso.ip + ":" + bso.po + "/slither");`
Also, do you have trouble connecting to the server or getting a response from it?

**Comment by Stan-Stani** [comment]
I was able to connect using node's Net module but couldn't get any sort of response from the server, but now that I realize I have to establish a websocket connection I have to figure out how to do that in node. I'll probably just use some sort of library from npm.

**Comment by Stan-Stani** [comment]
I'm still having some trouble. I'm still not getting a response (more specifically I get "Error: Socket hang up" using the [WebSocket Library for Node.js](https://github.com/theturtle32/WebSocket-Node)) when trying to connect to a slither.io server, even when I use the websocket library from npm. I know my code works because if I switch the ip to my own local test ws server, I get a response. However, when I try it with my remote server (which is running socket.io) I don't get a response. I must still be missing something.

I've noticed by watching how my browser initiates a ws connection for slither.io that an http upgrade is involved. Do I need to connect with http first and then switch to ws? Any ideas?

**Comment by Mat2095** [comment]
I think what you see is the websocket handshake (https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake). It should by handled by the library.

**Comment by Stan-Stani** [comment]
Yes the library is handling it. I talked to some other people and they said the server might require a specific origin header or cookies. Is that the case?

**Comment by Mat2095** [comment]
Yes, the origin in the header has to be http://slither.io. And also some user-agents might be blacklisted by CloudFlare.

**Comment by Stan-Stani** [comment]
Ok, great. Thanks, Mat2095! I've been able to connect and have the server start sending data a couple times but now I get a connect error of "Sec-WebSocket-Accept header from server didn't match expected value of ..." Any ideas? Do I need to specify a specific algorithm for the key?

I've tried to connect to a different server and it worked the first time, but the second time I got the same error. I've waited awhile and tried again and at least once I was able to connect again. Does this have something to do with me not ending the connection properly? I just let it timeout on the server side and don't send it any data after the initial connection and username and ping packets.

**Comment by Mat2095** [comment]
No, the algorithm for the key is job of the WebSocket library.
You're not the first to encounter this error, see #47. Like I've said there, it is not unusual to have to try to connect to about 5 to 10 servers until you find one that is actually available.
If that does not help, you might want to ask @agarioBotDev, who apparently has solved this. (I haven't written a single JavaScript line in my life, my Slither Client is in Java and I don't have this error there, so I probably can't help you any further)

**Comment by Stan-Stani** [comment]
Alright, thanks for everything.
