### ISSUE TITLE
Is fpsls and fmlts client-side?

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#51]
I am trying to create a server for slither.io but I am stuck getting the player's score. Is `Math.floor(15 * (fpsls[snake.sct] + snake.fam / fmlts[snake.sct] - 1) - 5) / 1` client-side and if so, how do I convert it to be server side. If not, can I just stick this code in to get the score. I can't seem to find any docs for fpsls and fmlts online so I don't know what to do with it

**Comment by Mat2095** [comment]
You need fpsls and fmlts on both sides. On the client for displaying all lengths, on the server for finding the top 10 players (maybe other stuff, too).
Fpsls and fmlts can be calculated from the mscps value (usually 411), just seach for "setMscps" in the original client-code.

**Comment by RowanHarley** [comment]
ok, thanks!

**Comment by RowanHarley** [comment]
what does snake.sct stand for @Mat2095 do you know?

**Comment by Mat2095** [comment]
[Here](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_a_detail) is the description: sct is the number of body-parts.

**Comment by RowanHarley** [comment]
thanks!
