### ISSUE TITLE
Get Sectors

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#55]
Are Sectors meant to be at certain places or can these be put at random positions

**Comment by Mat2095** [comment]
Sectors have (and are identified with) x and y coordinates. The width and height are given in the init-packet (currently 480). So no, they can't be put at random positions ;)

**Comment by RowanHarley** [comment]
Ok, thanks!

**Comment by RowanHarley** [comment]
Should I use sector_count_along _edge to get all the sectors

**Comment by Mat2095** [comment]
`sector_count_along _edge` is unused in the game, and nobody knows exactly what it actually does.
If you want to get the number of sectors (in one dimension), just use `game_radius*2/sector_size` (which currently equals `21600*2/480 = 90`).

**Comment by RowanHarley** [comment]
ok, should I store the x and y values in an array so that I can spawn food in that sector?

**Comment by Mat2095** [comment]
I assume you are talking about a client?

**Comment by RowanHarley** [comment]
I'm talking about server-side. Should I store the sectors there so that I know when the player moves into a new sector

**Comment by Mat2095** [comment]
That depends on your implementation. You could say, the world contains sectors and sectors contain food, or you just say the world contains food. In that case you don't have sectors at all, but updating the clients would be more complicated. Also the first way might have better performance.

**Comment by RowanHarley** [comment]
ya, I'm thinking about performance because no-one likes a server they can barely play on
