### ISSUE TITLE
SaveVictoryMessage: Is there something missing?

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#61]
I was looking at the [SaveVictoryMessage](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#packet-savevictorymessage) and I couldn't help but notice that there was no byte sent for the players username. Is there something missing?

**Comment by Mat2095** [comment]
No, this should be correct.
You send the username at the start of the game. It stays the same for the client during the connection, so there is no need to resend it for the VictoryMessage (or ping, or updateOwnSnake).
Also I'd like to point out, that I haven't seen a Victory-Message for weeks, I guess this feature got scrapped.

**Comment by RowanHarley** [comment]
Maybe, but I still see it in the html code. I think they're trying to fix the hackings it got earlier
