### ISSUE TITLE
What's the difference between the different case letters?

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#62]
I've been looking through the protocol and I'm seeing a lot of packets with different cases, like packet  [g](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#packet-g-move-snake) and [G](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_G_detail)? What's the difference between them? Does it matter which one I use?

**Comment by Mat2095** [comment]
(Note: I assume you view this from the server-side!)

No, they are all different (despite the different packet-format):
- e, E, 3, 4 and 5 all update a snake in some way. Depending on the packet-type and the packet-length, different variables are updated. You could just update all of them every time, but to minimize the amount of data sent, you should only send the ones that actually changed.
- g/G and n/N move a snake. G/N are relative coordinates and need two bytes less (again, to minimize data sent). You obviously can't always send relatives coordinates (clients might drift from the server), so from time to time you should send the absolute coordinates.
- w/W: adding vs removing sectors, this should be clear
- f/F: f is for food that spawns naturally, F is for food that existed before, but just now got into the range of the player. F can contain multiple food-entities, f only one. The spawning-animation is slower for food received from an f-packet.

**Comment by RowanHarley** [comment]
Ok, thanks for the help!
