### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GrumpyOet** [ClitherProject/Slither.io-Protocol#63]
i found a project from @RowanHarley for a slither.io server but what the problem is when you load it the snake go really fast and if you take a look at the /src/messages/movement.js file.
take a look in that file an you see this
`var arr = new Uint8Array(9);`

the 9 is for the speed but when i change it to any thing else the snake get removed from the game.

**Comment by GrumpyOet** [comment]
it have the G move speed charCode

**Comment by Mat2095** [comment]
9 is the lenth of the array and it should be 7 (unless it gets shorten somewhere else). The G packet is for position, not speed.
Apart from that, if any, this is a problem of the server-implementation, not something about the protocol. Therefore this issue belongs there and not here.
