### ISSUE TITLE
Packet 'v' doesn't work on it's own

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#64]
It seems like the packet 'v' doesn't seem to work on it's own. Is it meant to be paired with another packet. Note: I'm trying to send the packet 'v' at random times. Does the snake have to actually die for me to send this packet?

**Comment by Mat2095** [comment]
Hm, kind of. 'v' just tells the client that the game is over, the player-snake is then removed with an 's' packet and the actual connection is closed a few seconds later.
What is the behavior you get, what the one you expect?

**Comment by RowanHarley** [comment]
I musn't be removing it with the 's' packet. Didn't even know I needed to use that
