### ISSUE TITLE
Movement packet "g", how does it work?

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Slither.io-Protocol#72]
How do that packets "g" and "G" work? I've been debugging slither.io's client code but I don't see patterns in the way they're sent. The only difference I see is that the packet "g" isn't sent too often in the game so I can guess that this is for lag simulation.

**Comment by Mat2095** [comment]
They both move the snake while not making it longer. 'G' is relative to the head and therefore doesn't need large numbers so one byte per coordinate is enough. 'g' is absolute and therefore has to be able to handle large numbers so you need two bytes per coordinate. To minimize bandwidth while making sure the client doesn't drift from the server you should send 'G' packets mostly and 'g' packets only every then and now.
