### ISSUE TITLE
angle  to radians?

### ISSUE THREAD

**Issue by chenny** [ClitherProject/Slither.io-Protocol#77]
why not **angle \* Math.PI /180** but **angle \* 2*Math.PI / 251** ?

**Comment by Mat2095** [comment]
The angle is just a single byte, so it has values from 0 to 255. Some of these values are reserved (for speed-mode e.g.), so even less values are possible, being 0 to 250, so 251 values. A whole circle in radians is 2*pi, in slither-measurement it is 251. This results in the given formula.

**Comment by chenny** [comment]
tks
