### ISSUE TITLE
How to get Snake's head coordinate

### ISSUE THREAD

**Issue by BadPlayer555** [ClitherProject/Slither.io-Protocol#83]
Simply what the title says. I want to know how to get the head.x and y so that I can get the Pos of the snake

**Comment by Mat2095** [comment]
When you get an (["s"-Packet](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_s_detail), the two values after the name are x and y of the tail. After that you get relative coordinates for each body-part (relative to the previous part). The last relative coordinates are the head.

When you get an "g", "n", "G", or "N" packet, you get an update for a snake-(head)-position; "G" and "N" are relative to the old head-position, "g" and "n" are absolute. If you only care about the head, the difference between "g" vs "n" and "G" vs "N" is not relevant to you.

Notice that this is not 100% exact, there are other factory (like there is a method that reduces the lag felt, but this hasn't been decoded), but it is good enough for a basic custom client.

**Comment by BadPlayer555** [comment]
How do I know what is the last two bytes are the head?

**Comment by Mat2095** [comment]
I don't understand your question grammatically.

Anyway, forget the first part of my previous answer, the head coordinates are directly there, bytes 18-20 for x and 21-23 for y.
```java
double x = ((data[18] << 16) | (data[19] << 8) | data[20]) / 5.0;
double y = ((data[21] << 16) | (data[22] << 8) | data[23]) / 5.0;
```
See [here](https://github.com/Mat2095/MySlither/blob/master/src/de/mat2095/my_slither/MySlitherWebSocketClient.java#L514).

**Comment by Mat2095** [comment]
Is your question answered or do you need more help?

**Comment by BadPlayer555** [comment]
Actually my issues is not closed, my "G" packet is still not correct as I tested it with a userscript and the value is always 2 digits.

link: https://hastebin.com/uvetikinux.js help me

**Comment by Mat2095** [comment]
Hm, the code looks fine. You are ignoring the snake-id (index 3+4), so you can't tell which snake is moved. Could that be the problem?

**Comment by BadPlayer555** [comment]
Still same 😢 

Updated Userscript: 
https://hastebin.com/apihekofos.js

**Comment by Mat2095** [comment]
Ah, the problem is that you reset `headX` and `headY` to `0` with every packet received.
```javascript
var headX = 0;
var headY = 0;
```
(and most likely some other lines, too) needs to be outside of the event-listener-function.

**Comment by BadPlayer555** [comment]
Thx Man fixed. It is now fixed by removing checking is it the same snakeID and putting the variable outside the listener. 😄
