### ISSUE TITLE
Update to protocol 12

### ISSUE THREAD

**Issue by Mat2095** [ClitherProject/Slither.io-Protocol#89]
Current protocol is 12, the documentation should be adjusted to that.
However, protocol 11 is working with the current live servers.

**Comment by Mat2095** [comment]
Hm, it seems like the current official client only supports protocol 11, however it is possible to request protocol 12, so the official server supports version 12. But since there is no client, reverse-engineering version 12 would be quite hard and not yet necessary.

**Comment by Mat2095** [comment]
There are some recent update-notes on android:
- Added cosmetic support
- Improved game play speed.
plus, some "enter code" functionality

**Comment by argmanda** [comment]
tengo los bots pero no me siguen solo van asia la derecha alguna solucion a eso

**Comment by Mat2095** [comment]
@argmanda Please write in English.

**Comment by argmanda** [comment]
Mat2095  sorry and fix the bots work fine .. thanks anyway
https://imgur.com/bVaiVrG

**Comment by Mat2095** [comment]
I think the mystery is partially solved. If you enter the username "bonkers", a button appears which lets you enter a 12-digit code. That code is checked on the server; if valid, cosmetics will be unlocked. The check can be bypassed, revealing all 32 cosmetics.
![ClipboarderTemp-14e99e4](https://user-images.githubusercontent.com/11258252/64571507-5b17fd80-d364-11e9-9ca1-d4f012238378.png)
The chosen cosmetic is only visible locally, but not for other players.
All that is done with the existing protocol version. Only two packet-types were added, for validating the code.

**Comment by sebakof** [comment]
Mat2095  How do I see the accessories? just show up to enter a code

**Comment by Mat2095** [comment]
@sebakof I modified the sourcecode using the chrome-extensioin "Resource Override".

1. There is an assignment `want_open_cosmetics = !1` that I changed to `want_open_cosmetics = true`. Then the cosmetics will be shown if you click the cancel-button on the enter-code-page.

2. There is a function `recalculateActivatedCosmetics` where I changed `actco.push(0);` to `actco.push(1);`, which will just enable all cosmetics.

**Comment by sebakof** [comment]
![Captura de pantalla (96)](https://user-images.githubusercontent.com/38825263/65354129-03dd1d00-dbef-11e9-8e9f-106c51558984.png)

**Comment by Mat2095** [comment]
`actco=Array(32).fill(1)`

**Comment by sebakof** [comment]
![Captura de pantalla (98)](https://user-images.githubusercontent.com/38825263/65354848-d8f3c880-dbf0-11e9-85fd-ab626355566b.png)
thanks friend for the help

**Comment by sebakof** [comment]
Mat2095 
thanks friend for the help, thanks friend for the help
