### ISSUE TITLE
Not getting all websocket messages

### ISSUE THREAD

**Issue by githubranduser** [ClitherProject/Slither.io-Protocol#90]
Howdy,

Title says it all. I'm not getting all the web socket packets. I'm not getting p, W, G (so far that I have noticed) but I get all the others (seemingly) fine.

I should get a, s, g, W, F, W, F, W, F, W, F, W, F (this is what the game itself does); after all the W and F packets, the client shoots over the first ping.

I get a, s, g, F (so no W), just F, F, F, F, F, F, F, etc.

Then I never get any G packet updates; so I can't correctly determine my x, y.

Then I noticed after I send the preInitResponse, it's like the server doesn't take anymore of my packets but continued to send me stuff. So I can watch my snake in game but it won't move (but I can see my server pushing the speed up packet, but nothing happens). As soon as I disconnect the websocket, the snake starts moving around like there is a player behind it but it's the game's AI taking over.

Ideas? The protocol version, I've tried, 10, 11, and 12.

Thanks

**Comment by Mat2095** [comment]
Hm, the G packet should not be a problem, as the g packet contains the position.

I can confirm the packets you get from the server should be something like 6, a, s, g, W, F, W, F, ...
No clue about why you wouldn't receive W-packets. I tried some stuff, but it either worked like normal or it didn't work at all.

**Comment by githubranduser** [comment]
When I get the snake position; I get the correct x,y (so this goes into the x, y) and the initial piece I stick into the body. When I get the g packet, the x is like 321 while the y is like 27132; I assumed based off the absoluteCoords that the g was absolute, so it should give me full x,y while I would expect the g to give me a differential of the x,y (so I can add in the head.x, head.y) but I seem to be getting what I would expect to get in the G as a g. It's kind of weird. I haven't figured it out yet.

-------- g --------
messageType: 103,
  id: 51924,
  x: 578,
  y: 2817,
  fam: 0,
  removeLast: true,
  flag: 'g',
  size: 11,
  original: Uint8Array [ 0, 232, 103, 202, 212, 2, 66, 11, 1, 221, 245 ] }
-------- g End --------
debug: [name] (IP:444):!! INCOMING !!:connect:onmessage:function:g:message received -> ègÊÔB Ýõ
debug: [name] (IP:444):!! INCOMING !!:connect:onmessage:function:f:message received -> éf�Ê`Qó
/
-------- g --------
{ messageType: 103,
  id: 51924,
  x: 578,
  y: 12033,
  fam: 0,
  removeLast: true,
  flag: 'g',
  size: 11,
  original: Uint8Array [ 0, 8, 103, 202, 212, 2, 66, 47, 1, 221, 38 ] }
-------- g End --------

This is right after a

**Comment by Mat2095** [comment]
Okay, something's wrong here. The g-packet is only 9 bytes long: 2 for the delta-time, 1 for the packet-type and for the id, x and y 2 bytes each. You shouldn't receive 11 bytes...

**Comment by Mat2095** [comment]
In fact, I just played a little and didn't receive ANY 11-byte packets...

**Comment by githubranduser** [comment]
yeah, it's weird, I had to turn the length portion off, all my packets were longer than expected. So it must be something I'm doing; I just don't know what it is yet. Right now it's just a mesh of code, so it's hard to locate what I'm looking for.

**Comment by githubranduser** [comment]
So, I found why I wasn't getting everything. It's because I wasn't actually including the protocol_version; so it was allowing me to connect without it but it wasn't returning the expected data. Now I have it correct and I'm getting everything. Thanks!!
