### ISSUE TITLE
Custom skin colors?

### ISSUE THREAD

**Issue by dickbalaska** [ClitherProject/Slither.io-Protocol#91]
Has anyone worked out what the colors are in the custom skin data?

It is incredibly tedious to try to run two clients and keep the official custom skin snake alive so I can look at it (and receive its data) with my client.

**Comment by Mat2095** [comment]
![ClipboarderTemp-1a02534](https://user-images.githubusercontent.com/11258252/61174610-f712cc00-a5a2-11e9-8b04-3d0180698df8.png)
Looks pretty straightforward, except ids 36 and 38 are invalid.
